# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import timer_service_pb2 as timer__service__pb2


class TimerServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterTimer = channel.unary_stream(
                '/timer.TimerService/RegisterTimer',
                request_serializer=timer__service__pb2.TimerRequest.SerializeToString,
                response_deserializer=timer__service__pb2.TimerResponse.FromString,
                )


class TimerServiceServicer(object):
    """Service definition
    """

    def RegisterTimer(self, request, context):
        """Registers a timer with a specified duration and supports server streaming for responses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterTimer': grpc.unary_stream_rpc_method_handler(
                    servicer.RegisterTimer,
                    request_deserializer=timer__service__pb2.TimerRequest.FromString,
                    response_serializer=timer__service__pb2.TimerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timer.TimerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimerService(object):
    """Service definition
    """

    @staticmethod
    def RegisterTimer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/timer.TimerService/RegisterTimer',
            timer__service__pb2.TimerRequest.SerializeToString,
            timer__service__pb2.TimerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
